<template>
  <CodeEditor
    width="100%"
    :read_only="true"
    :wrap_code="true"
    :language_selector="true"
    :languages="editorLanges($props.lang)"
    :value="$props.code"
  ></CodeEditor>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import CodeEditor from "simple-code-editor";

export default defineComponent({
  props: {
    code: String,
    lang: {
      type: String as PropType<ELanguages>,
    },
  },
  components: {
    CodeEditor,
  },
  setup(props) {
    const editorLanges = (lang: ELanguages) => {
      return [[lang, lang]];
    };

    return { editorLanges };
  },
});

export enum ELanguages {
  "1c" = "1c",
  "abnf" = "abnf",
  "accesslog" = "accesslog",
  "actionscript" = "actionscript",
  "ada" = "ada",
  "angelscript" = "angelscript",
  "apache" = "apache",
  "applescript" = "applescript",
  "arcade" = "arcade",
  "arduino" = "arduino",
  "armasm" = "armasm",
  "xml" = "xml",
  "asciidoc" = "asciidoc",
  "aspectj" = "aspectj",
  "autohotkey" = "autohotkey",
  "autoit" = "autoit",
  "avrasm" = "avrasm",
  "awk" = "awk",
  "axapta" = "axapta",
  "bash" = "bash",
  "basic" = "basic",
  "bnf" = "bnf",
  "brainfuck" = "brainfuck",
  "c" = "c",
  "cal" = "cal",
  "capnproto" = "capnproto",
  "ceylon" = "ceylon",
  "clean" = "clean",
  "clojure" = "clojure",
  "clojure-repl" = "clojure-repl",
  "cmake" = "cmake",
  "coffeescript" = "coffeescript",
  "coq" = "coq",
  "cos" = "cos",
  "cpp" = "cpp",
  "crmsh" = "crmsh",
  "crystal" = "crystal",
  "csharp" = "csharp",
  "csp" = "csp",
  "css" = "css",
  "d" = "d",
  "markdown" = "markdown",
  "dart" = "dart",
  "delphi" = "delphi",
  "diff" = "diff",
  "django" = "django",
  "dns" = "dns",
  "dockerfile" = "dockerfile",
  "dos" = "dos",
  "dsconfig" = "dsconfig",
  "dts" = "dts",
  "dust" = "dust",
  "ebnf" = "ebnf",
  "elixir" = "elixir",
  "elm" = "elm",
  "ruby" = "ruby",
  "erb" = "erb",
  "erlang-repl" = "erlang-repl",
  "erlang" = "erlang",
  "excel" = "excel",
  "fix" = "fix",
  "flix" = "flix",
  "fortran" = "fortran",
  "fsharp" = "fsharp",
  "gams" = "gams",
  "gauss" = "gauss",
  "gcode" = "gcode",
  "gherkin" = "gherkin",
  "glsl" = "glsl",
  "gml" = "gml",
  "go" = "go",
  "golo" = "golo",
  "gradle" = "gradle",
  "groovy" = "groovy",
  "haml" = "haml",
  "handlebars" = "handlebars",
  "haskell" = "haskell",
  "haxe" = "haxe",
  "hsp" = "hsp",
  "http" = "http",
  "hy" = "hy",
  "inform7" = "inform7",
  "ini" = "ini",
  "irpf90" = "irpf90",
  "isbl" = "isbl",
  "java" = "java",
  "javascript" = "javascript",
  "jboss-cli" = "jboss-cli",
  "json" = "json",
  "julia" = "julia",
  "julia-repl" = "julia-repl",
  "kotlin" = "kotlin",
  "lasso" = "lasso",
  "latex" = "latex",
  "ldif" = "ldif",
  "leaf" = "leaf",
  "less" = "less",
  "lisp" = "lisp",
  "livecodeserver" = "livecodeserver",
  "livescript" = "livescript",
  "llvm" = "llvm",
  "lsl" = "lsl",
  "lua" = "lua",
  "makefile" = "makefile",
  "mathematica" = "mathematica",
  "matlab" = "matlab",
  "maxima" = "maxima",
  "mel" = "mel",
  "mercury" = "mercury",
  "mipsasm" = "mipsasm",
  "mizar" = "mizar",
  "perl" = "perl",
  "mojolicious" = "mojolicious",
  "monkey" = "monkey",
  "moonscript" = "moonscript",
  "n1ql" = "n1ql",
  "nestedtext" = "nestedtext",
  "nginx" = "nginx",
  "nim" = "nim",
  "nix" = "nix",
  "node-repl" = "node-repl",
  "nsis" = "nsis",
  "objectivec" = "objectivec",
  "ocaml" = "ocaml",
  "openscad" = "openscad",
  "oxygene" = "oxygene",
  "parser3" = "parser3",
  "pf" = "pf",
  "pgsql" = "pgsql",
  "php" = "php",
  "php-template" = "php-template",
  "plaintext" = "plaintext",
  "pony" = "pony",
  "powershell" = "powershell",
  "processing" = "processing",
  "profile" = "profile",
  "prolog" = "prolog",
  "properties" = "properties",
  "protobuf" = "protobuf",
  "puppet" = "puppet",
  "purebasic" = "purebasic",
  "python" = "python",
  "python-repl" = "python-repl",
  "q" = "q",
  "qml" = "qml",
  "r" = "r",
  "reasonml" = "reasonml",
  "rib" = "rib",
  "roboconf" = "roboconf",
  "routeros" = "routeros",
  "rsl" = "rsl",
  "ruleslanguage" = "ruleslanguage",
  "rust" = "rust",
  "sas" = "sas",
  "scala" = "scala",
  "scheme" = "scheme",
  "scilab" = "scilab",
  "scss" = "scss",
  "shell" = "shell",
  "smali" = "smali",
  "smalltalk" = "smalltalk",
  "sml" = "sml",
  "sqf" = "sqf",
  "sql" = "sql",
  "stan" = "stan",
  "stata" = "stata",
  "step21" = "step21",
  "stylus" = "stylus",
  "subunit" = "subunit",
  "swift" = "swift",
  "taggerscript" = "taggerscript",
  "yaml" = "yaml",
  "tap" = "tap",
  "tcl" = "tcl",
  "thrift" = "thrift",
  "tp" = "tp",
  "twig" = "twig",
  "typescript" = "typescript",
  "vala" = "vala",
  "vbnet" = "vbnet",
  "vbscript" = "vbscript",
  "vbscript-html" = "vbscript-html",
  "verilog" = "verilog",
  "vhdl" = "vhdl",
  "vim" = "vim",
  "wasm" = "wasm",
  "wren" = "wren",
  "x86asm" = "x86asm",
  "xl" = "xl",
  "xquery" = "xquery",
  "zephir" = "zephir",
}

export interface codeReutrnType {
  title?: string;
  html?: string;
  code?: { code: string; lang: ELanguages }[];
}
</script>

<style lang="scss">
.code-margin {
  margin: 1rem 0;
}
</style>
