# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Vue delopy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 저장소 체크아웃
      - uses: actions/checkout@v3

      # 노드 환경 설정
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"

      # 배포 .env 파일 생성 & secrets를 이용한 env값추가
      - name: vue depoly product Create .env file
        run: |
          echo "VUE_APP_TEST=$VUE_APP_TEST" >> .env.production
          echo "VUE_APP_PORTFOLIO=$VUE_APP_PORTFOLIO" >> .env.production

        env:
          VUE_APP_TEST: "env 파일 Test"
          VUE_APP_PORTFOLIO: ${{ secrets.PORTFOLIO }}

        # Post Use Node.js 14 빌드 Cache오류
      - name: Post Node.js Cache오류
        run: mkdir -p /home/runner/.npm
        continue-on-error: true

        # Netlify 배포
      # - name: Netlify Deploy
      #   # You may pin to the exact commit or the version.
      #   # uses: jsmrcaga/action-netlify-deploy@53de32e559b0b3833615b9788c7a090cd2fddb03
      #   uses: jsmrcaga/action-netlify-deploy@v1.8.0
      #   with:
      #     # Auth token to use with netlify
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     # Your Netlify site id
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     # Directory where built files are stored
      #     build_directory: ./dist

      #     NETLIFY_DEPLOY_TO_PROD: true
      #     # node version
      #     node_version: 14

      # githubpages 배포 설정

      # # 패키지 설치
      # - name: 패키지 설치
      #   run: npm install

      # # 빌드
      # - name: 빌드
      #   run: npm run build

      # 깃 허브 페이지 배포
      # - name: GitHub Pages action
      #   # You may pin to the exact commit or the version.
      #   # uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
      #   uses: peaceiris/actions-gh-pages@v3.7.3
      #   with:
      #     # Set a generated GITHUB_TOKEN for pushing to the remote branch.
      #     github_token: ${{ secrets.TOKEN }}
      #     # Set custom domain
      #     cname:
      #       study.kimjuchan97.site
      #       # Set a target branch for deployment.
      #     publish_branch: gh-pages
      #     # Set an input directory for deployment.
      #     publish_dir: ./dist
